services:
  dotnet-hello-world-pipeline:
    build:
      context: ./dotnet-hello-world-pipeline
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - nginx-proxy-manager-external

networks:
  nginx-proxy-manager-external:
    external: true